### ISSUE TITLE
Connection aborted errors in Django

### ISSUE THREAD

**Issue by loicgasser** [DevCycleHQ/python-server-sdk#19]
Hi I am using Django and I followed the setup instructions you provided in your documentation.

When working locally everything seems to work fine, however when the app is deployed I am experiencing instability when using the DevCycle SDK. (10-20% of the time)

My guess is that this is related to the `pool_manager`  in `urllib3 `.

I found a related ticket in urllib3
https://github.com/psf/requests/issues/4937

It seems that implementing a single retry works for most people.

Could it be a throttling mechanism on your side? API rate?
Any help would be appreciated thanks. 

Here is my startup command.

`gunicorn --bind 0.0.0.0:9000 core.asgi:application -w 4 -k uvicorn.workers.UvicornWorker`

```
name = "devcycle-python-server-sdk"
version = "1.2.2"
```

```
name = "urllib3"
version = "1.26.16"
```

```
name = "django"
version = "4.2.1"
```

```
name = "gunicorn"
version = "20.1.0"
```

```
name = "uvicorn"
version = "0.22.0"
```

```
Traceback (most recent call last):
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/src/core/flags/sdk/client.py", line 21, in get_dvc_variables
    variables = client.all_variables(user_data)
File "/opt/pysetup/.venv/lib/python3.8/site-packages/devcycle_python_sdk/api/dvc_client.py", line 291, in all_variables
    (data) = self.all_variables_with_http_info(user, **kwargs)  # noqa: E501
File "/opt/pysetup/.venv/lib/python3.8/site-packages/devcycle_python_sdk/api/dvc_client.py", line 355, in all_variables_with_http_info
    return self.api_client.call_api(
File "/opt/pysetup/.venv/lib/python3.8/site-packages/devcycle_python_sdk/api_client.py", line 316, in call_api
    return self.__call_api(resource_path, method,
File "/opt/pysetup/.venv/lib/python3.8/site-packages/devcycle_python_sdk/api_client.py", line 148, in __call_api
    response_data = self.request(
File "/opt/pysetup/.venv/lib/python3.8/site-packages/devcycle_python_sdk/api_client.py", line 358, in request
    return self.rest_client.POST(url,
File "/opt/pysetup/.venv/lib/python3.8/site-packages/devcycle_python_sdk/rest.py", line 268, in POST
    return self.request("POST", url,
File "/opt/pysetup/.venv/lib/python3.8/site-packages/devcycle_python_sdk/rest.py", line 161, in request
    r = self.pool_manager.request(
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/opt/pysetup/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
````

**Comment by leslie-lau** [comment]
Hi @loicgasser, thanks for writing in! 

Our Team will be working on upgrades to the Python SDK as our next roadmap item and we'll also ensure that this issue is also resolved with those upgrades. We expect to start the work in the coming days and have the new updates fully rolled out in a couple of weeks. 

Would this timeline be sufficient for you and your team to work with, or is this issue a blocker for you at this time?

**Comment by loicgasser** [comment]
Hi thank you for the quick response.
The solution for us at this point is not to use the SDK, and query DevCycle API directly using a `"safer"` approach.

While I have your attention, we've also had our share of problems with
https://github.com/DevCycleHQ/python-server-sdk/blob/main/devcycle_python_sdk/api_client.py#L68

AK starting the `ThreadPool` outside of the `settings.py`. We learned the hard way we were creating a `ThreadPool` under the hood (as problems yet again don't show up locally).

We are not using the async feature so I would to see a world were we could also avoid the creation of a thread pool if we don't plane on using it.

 It's probably out of scope but python 3 is async in nature and there are some lighter solutions out there if we want to use python asynchronously. I understand the reason for this optimization historically, but we would probably be better served with something like this:
https://github.com/encode/httpx

**Comment by leslie-lau** [comment]
Hey @loicgasser that sounds good, we'll be sure to update you when our Python SDK updates have been made. We'll be re-evaluating the whole SDK, including how we're handling the Thread Pools so that should see some changes. Thanks for the additional info!

**Comment by leslie-lau** [comment]
Hi @loicgasser,

We've released a new version of the DevCycle Cloud Bucketing Python SDK, v2.0.0. This is a major release that contains improvements to the underlying logic in the SDK. You can find out more by visiting the following link.

Release: https://github.com/DevCycleHQ/python-server-sdk/releases/tag/v2.0.0

**Notable changes**
- Classnames have changed! Be sure to check out our updated documentation to ensure that you're using the new SDK method names. Hint: check out the getting-started page and section on defining user attributes.
- Removed Support for Python 2
- Removed thread pooling rest client

We've updated our Django Sample App to v2.0.0 which will allow you to use Django middleware to initialize DevCycle, instead of initializing DevCycle in your settings.py. We recommend checking that out as well.

Sample App: https://github.com/DevCycleHQ/python-django-example-app

Let us know if you have any questions on the release!

**Comment by loicgasser** [comment]
Great thanks

**Comment by cdruxerman** [comment]
@loicgasser we're going to mark this as resolved. Let us know if you run into any further issues.
